
service: water

plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs12.x


functions:
  hello:
    handler: api/createProfile.handler
    description: sks a  new profile
    events:
      - http:
          path: profiles
          method: post
          cors:
            origin: '*'

