
service: water

plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs12.x


functions:
  createProfile:
    handler: api/createProfile.handler
    description: sks a  new profile
    events:
      - http:
          path: profiles
          method: post
          cors:
            origin: '*'
    
  Login:
    handler: api/login.handler
    description: logins and gets a users profile and token
    events:
       - http:
            path: profiles/login
            method: post
            cors:
               origin: '*'
